/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminCoursesRouteImport } from './routes/admin-courses'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AdminStudentsRouteImport } from './routes/admin-students'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentCoursesRouteImport } from './routes/student-courses'
import { Route as AdminCourseBuilderCourseIdRouteImport } from './routes/admin-course-builder.$courseId'
import { Route as AdminStudentProfileStudentIdRouteImport } from './routes/admin-student-profile.$studentId'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin-courses',
  path: '/admin-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin-students',
  path: '/admin-students',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/student-courses',
  path: '/student-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCourseBuilderCourseIdRoute =
  AdminCourseBuilderCourseIdRouteImport.update({
    id: '/admin-course-builder/$courseId',
    path: '/admin-course-builder/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminStudentProfileStudentIdRoute =
  AdminStudentProfileStudentIdRouteImport.update({
    id: '/admin-student-profile/$studentId',
    path: '/admin-student-profile/$studentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-courses': typeof AdminCoursesRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-students': typeof AdminStudentsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/student-courses': typeof StudentCoursesRoute
  '/admin-course-builder/$courseId': typeof AdminCourseBuilderCourseIdRoute
  '/admin-student-profile/$studentId': typeof AdminStudentProfileStudentIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-courses': typeof AdminCoursesRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-students': typeof AdminStudentsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/student-courses': typeof StudentCoursesRoute
  '/admin-course-builder/$courseId': typeof AdminCourseBuilderCourseIdRoute
  '/admin-student-profile/$studentId': typeof AdminStudentProfileStudentIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-courses': typeof AdminCoursesRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-students': typeof AdminStudentsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/student-courses': typeof StudentCoursesRoute
  '/admin-course-builder/$courseId': typeof AdminCourseBuilderCourseIdRoute
  '/admin-student-profile/$studentId': typeof AdminStudentProfileStudentIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-courses'
    | '/admin-dashboard'
    | '/admin-students'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/student-courses'
    | '/admin-course-builder/$courseId'
    | '/admin-student-profile/$studentId'
    | '/course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-courses'
    | '/admin-dashboard'
    | '/admin-students'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/student-courses'
    | '/admin-course-builder/$courseId'
    | '/admin-student-profile/$studentId'
    | '/course/$courseId'
  id:
    | '__root__'
    | '/'
    | '/admin-courses'
    | '/admin-dashboard'
    | '/admin-students'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/student-courses'
    | '/admin-course-builder/$courseId'
    | '/admin-student-profile/$studentId'
    | '/course/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  AdminCourseBuilderCourseIdRoute: typeof AdminCourseBuilderCourseIdRoute
  AdminStudentProfileStudentIdRoute: typeof AdminStudentProfileStudentIdRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-courses': {
      id: '/admin-courses'
      path: '/admin-courses'
      fullPath: '/admin-courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-students': {
      id: '/admin-students'
      path: '/admin-students'
      fullPath: '/admin-students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-courses': {
      id: '/student-courses'
      path: '/student-courses'
      fullPath: '/student-courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-course-builder/$courseId': {
      id: '/admin-course-builder/$courseId'
      path: '/admin-course-builder/$courseId'
      fullPath: '/admin-course-builder/$courseId'
      preLoaderRoute: typeof AdminCourseBuilderCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-student-profile/$studentId': {
      id: '/admin-student-profile/$studentId'
      path: '/admin-student-profile/$studentId'
      fullPath: '/admin-student-profile/$studentId'
      preLoaderRoute: typeof AdminStudentProfileStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  AdminCourseBuilderCourseIdRoute: AdminCourseBuilderCourseIdRoute,
  AdminStudentProfileStudentIdRoute: AdminStudentProfileStudentIdRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
